version: "3.9"
services:
  votosdb:
    build:
      context: ./SQL
      dockerfile: Dockerfile
    container_name: votosdb
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'estuardo'
      MYSQL_PASSWORD: 'password'
    networks:
      - p_front
      - p_grpc
      - p_redis
    ports:
      - "3307:3306"
    
  votosgrpcs:
    build:
      context: ./gRPC/Server
      dockerfile: Dockerfile
    container_name: votosgrpcs
    restart: "on-failure"
    env_file: ./.env
    environment:
      HOST: votosdb
      USER_NAME: $USER_NAME
      PASSWORD: $PASSWORD
      DATABASE: $DATABASE
    networks:
      - p_grpc
    depends_on:
      - votosdb
  
  votosgrpcc:
    build:
      context: ./gRPC/Client
      dockerfile: Dockerfile
    container_name: votosgrpcc
    restart: "on-failure"
    environment:
      HOST: votosgrpcs
    ports:
      - "3001:3001"
    networks:
      - p_grpc
    depends_on:
      - votosgrpcs

  redis:
    build:
      context: ./Redis/Redis-server
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - p_redis
    ports:
      - "6378:6379"

  redis-sub:
    build:
      context: ./Redis/redissub
      dockerfile: Dockerfile
    container_name: redis-sub
    restart: "on-failure"
    networks:
      - p_redis
    depends_on:
      - redis
      - votosdb

  redis-pub:
    build:
      context: ./Redis/redispub
      dockerfile: Dockerfile
    container_name: redis-pub
    restart: "on-failure"
    networks:
      - p_redis
    ports:
      - "8016:8016"
    depends_on:
      - redis

  votosapi:
    restart: "on-failure"
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: votosapi
    env_file: ./.env
    environment:
      HOST: votosdb
      USER_NAME: $USER_NAME
      PASSWORD: $PASSWORD
      DATABASE: $DATABASE
    networks:
      - p_front
      - p_redis
    depends_on:
      - votosdb
  
  votosreact:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: votosreact
    environment:
      REACT_APP_API: ""
    ports:
      - "3000:3000"
    networks:
      - p_front

networks:
  p_front:
  p_grpc:
  p_redis: