apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: votosdb
  labels:
    app: votosdb
  namespace: proyectoso1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: votosdb
  name: votosdb
  namespace: proyectoso1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votosdb
  template:
    metadata:
      labels:
        app: votosdb
    spec:
      containers:
      - image: estuardosonu/votosdb
        imagePullPolicy: Always
        name: votosdb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_USER
            value: "estuardo"
          - name: MYSQL_PASSWORD
            value: "password"
        ports:
          - containerPort: 3306
            name: votosdb
        volumeMounts:
          - name: mysql-volumen
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volumen
          persistentVolumeClaim:
            claimName: votosdb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: votosdb
  name: votosdb
  namespace: proyectoso1
spec:
  type: LoadBalancer
  ports:
    - name: votosdb
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: votosdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: proyectoso1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: estuardosonu/redis
        imagePullPolicy: Always
        name: redis
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: proyectoso1
spec:
  type: LoadBalancer
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis